apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-management-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-management-k8s
  template:
    metadata:
      labels:
        app: course-management-k8s
    spec:
      containers:
        - name: course-management-k8s
          image: course-student-management:v3
          ports:
            - containerPort: 7000
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: postgres-config1
---
apiVersion: v1
kind: Service
metadata:
  name: course-management-k8s-svc
spec:
  selector:
    app: course-management-k8s
  ports:
    - protocol: TCP
      port: 7000
      nodePort: 30089
  type: NodePort



