apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-deployement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course
  template:
    metadata:
      labels:
        app: course
    spec:
      containers:
        - name: course
          image: course-management/course
---
apiVersion: v1
kind: Service
metadata:
  name: course-clustorip-service
spec:
  selector:
    app: course
  ports:
    - name: course
      protocol: TCP
      port: 7000
      targetPort: 7000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tda-front-deployement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tda-front
  template:
    metadata:
      labels:
        app: tda-front
    spec:
      containers:
        - name: tda-front
          image: nextjs/tda-front
---
apiVersion: v1
kind: Service
metadata:
  name: tda-front-service
spec:
  selector:
    app: tda-front
  ports:
    - name: tda-front
      protocol: TCP
      port: 5000
      targetPort: 5000