apiVersion: v1
kind: Service
metadata:
  name: course-service
spec:
  type: NodePort
  selector:
    app: course
  ports:
    - name: course
      protocol: TCP
      port: 7000
      targetPort: 7000