apiVersion: apps/v1
kind: Deployment
metadata:
  name: tda-front-deployement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tda-front-end
  template:
    metadata:
      labels:
        app: tda-front-end
    spec:
      containers:
        - name: tda-front
          image: helloworld:v1
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: tda-front-service
spec:
  selector:
    app: tda-front-end
  ports:
    - name: tda-front
      protocol: TCP
      port: 5000
      nodePort: 30090
  type: NodePort
#      targetPort: 5000


