apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./kubernates-infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: course-registration
      context: course-management
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: tda-front-end
      context: tda-v2-front-end
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .