apiVersion: v1
kind: Service
metadata:
  name: tda-front-service
spec:
  type: NodePort
  selector:
    app: tda-front
  ports:
    - name: tda-front
      protocol: TCP
      port: 5000
      targetPort: 5000